### ISSUE TITLE
Joint interface cannot manage empty goals

### ISSUE THREAD

**Issue by gaya-** [SemRoCo/giskard_examples#37]
If one arm gets a joint goal and the other one nil both arms move into the same goal configuration of one arm.

**Comment by airballking** [comment]
Could you please post the goal message retrieved using `rostopic echo ...`? Thanks.

Edit: I'd like to have the results of both:
`rostopic echo /whole_body_controller/goal -n 1`
`rostopic echo /controller_action_server/move/goal -n 1`

**Comment by gaya-** [comment]
The controller action server goal for the other arm is an empty vector and the type in joint command I fixed the bug on CRAM side, so we can look into this after the demo.

**Comment by airballking** [comment]
Does this mean that you found the error on the client side?

**Comment by gaya-** [comment]
No, I'm just sending current joint state as the goal for the other arm.

**Comment by airballking** [comment]
Seems like the controller was not properly used. Closing the issue/
