### ISSUE TITLE
Error in boxy_interactive_markers.launch

### ISSUE THREAD

**Issue by mgvargas** [SemRoCo/giskard_examples#49]
The launch file tries to include `boxy.launch` from the `iai_naive_kinematics_sim` package, but the file doesn't exist (has been renamed?)

**Comment by airballking** [comment]
Thanks for reporting this! I am in the middle of refactoring the simulation setup. Right now, you have two options:

(1) If you just want to simulate Boxy, use the new setup: https://github.com/code-iai/iai_boxy_sim

(2) If you want to run giskard on a simulated Boxy, use the old setup. All relevant repos, i.e. giskard, giskard_msgs, giskard_examples, iai_naive_kinematics_sim, should be properly tagged. Use tag ```v0.0.1```

**Comment by airballking** [comment]
@mgvargas This should now be fixed. If you're still interested, please use the package ```giskard_boxy```. Some of the functionality moved there, and it depends on this repo.

Try this launch file: ```roslaunch giskard_boxy interactive_markers.launch```
